version: 0.2

environment_variables:
  plaintext:
    TEMPLATE_FILES: |
      poc-sample-aplication-cft-template.yaml
      poc-sample-infra-cft-template.yaml
      poc-sample-infra-init-cft-template.yaml
    CONFIG_FILES: |
      poc-sample-aplication-parameter.json
      poc-sample-infra-parameter.json

#https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#runtime-versions-buildspec-file
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      npm install jsonlint -g
  pre_build:
    commands:
      - echo "Validating CFN templates"
      - |
        for cfn_template in $TEMPLATE_FILES; do
          echo "Validating CloudFormation template file $cfn_template"
          aws cloudformation validate-template --template-body file://$cfn_template
        done
      - |
        for conf in $CONFIG_FILES; do
          echo "Validating CFN parameters config file $conf"
          jsonlint -q $conf
        done
  build:
    commands:
      - echo "do nothing"
artifacts:
  files:
    - poc-sample-aplication-cft-template.yamlc
    - poc-sample-infra-cft-template.yaml
    - poc-sample-infra-init-cft-template.yaml
    - poc-sample-aplication-parameter.json
    - poc-sample-infra-parameter.json
